### ISSUE TITLE
Nonce still too small with REST and Websocket even with multiple keys

### ISSUE THREAD

**Issue by androng** [bitfinexcom/bitfinex-api-node#116]
Could you provide an example that calls both an authenticated REST and Websocket endpoint? I receive "nonce too small" errors when I try to use them both. 

I could use Websockets only, but there is no websocket endpoint for listing historical orders or active positions. I need this because some of my orders seem to not generate notifications.  

I could use REST only, but I am afraid of getting rate limited.

**Comment by androng** [comment]
I just noticed too that there is no "new order" REST endpoint for API v2. This implies you intend for people to use API v2 with REST and Websocket traffic. Or should I use both API v1 and v2 simultaneously?

**Comment by androng** [comment]
I used two API keys and still get the same result. One key for websocket v2 and one for REST v2.

**Comment by androng** [comment]
This is my starting point. Both REST and WS used at the same time with authenticated calls.  

`/* 
	This is an example of an authenticated REST request. 
	This example fetches the last 25 orders on your account. 
 */
'use strict'

const BFX = require('bitfinex-api-node') 

const CREDENTIALS_REST = 
	{"API_KEY": '',
	 "API_SECRET": '' };
const CREDENTIALS_WS = 
	{"API_KEY": '',
	 "API_SECRET": '' };
	 
const opts = {  version: 2 }
const brest = new BFX(CREDENTIALS_REST.API_KEY, CREDENTIALS_REST.API_SECRET, opts).rest
const bws = new BFX(CREDENTIALS_WS.API_KEY, CREDENTIALS_WS.API_SECRET, opts).ws

const TIME_PROGRAM_STARTED = Date.now()
const ONE_DAY_IN_MS = 86400000 

const PAYLOAD = 
	{"start":TIME_PROGRAM_STARTED - ONE_DAY_IN_MS,
	"end": TIME_PROGRAM_STARTED, 
	"limit":25} /* If you try and request more than 25 then the API will return "invalid" */

brest.makeAuthRequest("/auth/r/orders/hist", PAYLOAD, function (ERROR, REPLY) {
    if (ERROR) {
    	console.log(ERROR)
    	return 
    }
    console.log(REPLY)
})

bws.on('open', () => {
	bws.auth();
})

bws.on('message', (msg) => {
    const CHANNEL_NUMBER = msg[0];
    if(0 == CHANNEL_NUMBER){
        /* It's an unhandled message from an authenticated channel  */
 		console.log(msg);
		
        return;
    }
})

bws.on('error', console.error);
`

The REST part does not work unless I specify in rest2.js that the nonce should be Date.now()*10000. But when I do that, the REST call works and the Websocket gives me this: 

`{ event: 'auth',
  status: 'FAILED',
  chanId: 0,
  code: 10114,
  msg: 'nonce: small' }`

**Comment by irvingliao** [comment]
I simply changed this line in rest2.js 
`this.nonce = Date.now() * 1000` 
and both v2 rest and v2 ws will work.

Did you change anything in ws2.js?
Cause the `this.nonce` is private in each class, if you change one of them, it shouldn't affect the other one.

**Comment by androng** [comment]
When I try my code from two comments ago with a fresh copy of this repo, I get

```
Error: StatusCodeError: 500 - ["error",10100,"apikey: invalid"]
    at rp.then.catch (/Users/andrew/Programming/bitcoin/node_modules/bitfinex-api-node/rest2.js:52:26)
    at tryCatcher (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/andrew/Programming/bitcoin/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
{ event: 'auth',
  status: 'FAILED',
  chanId: 0,
  code: 10114,
  msg: 'nonce: small' }
```

with library modification `this.nonce = Date.now() * 1000`, same error

So I tried with a fresh install of `npm install` instead. 

I get a different error message: 
```
Error: StatusCodeError: 500 - ["error",10114,"nonce: small"]
    at rp.then.catch (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bitfinex-api-node/rest2.js:64:26)
    at tryCatcher (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/andrew/Programming/bitcoin/tradingbot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
{ event: 'auth',
  status: 'FAILED',
  chanId: 0,
  code: 10114,
  msg: 'nonce: small' }
```

Only when I use `this.nonce = Date.now()*20000` in rest2.js and `const authNonce = (new Date()).getTime() * 10000` in ws2.js do I actually get two successful REST and Websocket calls. But subsequent REST calls fail with `Error: StatusCodeError: 500 - ["error",10114,"nonce: small"]`

So now I am really confused. I would really like it if the Bitfinex team just added a "historical orders" endpoint to Websocket so I don't have to use REST and deal with these parallel issues. I tried their two-key workaround and it doesn't solve the issue for me.

**Comment by androng** [comment]
I got rid of the nonce error! I think! I increase the REST nonce by 10 instead of 1 each time.

**Comment by f3rno** [comment]
Closing, we've bumped the nonce to `Date.now() * 1000` where applicable.
