### ISSUE TITLE
Error: Unhandled "error" event. ([object Object])

### ISSUE THREAD

**Issue by includeleec** [bitfinexcom/bitfinex-api-node#143]
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at BitfinexWS.emit (events.js:186:19)
    at BitfinexWS.onMessage (e:\00-crypto-currency\node_modules\bitfinex-api-node\ws.js:93:12)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (e:\00-crypto-currency\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (e:\00-crypto-currency\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (e:\00-crypto-currency\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (e:\00-crypto-currency\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (e:\00-crypto-currency\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (e:\00-crypto-currency\node_modules\ws\lib\WebSocket.js:139:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)

**Comment by f3rno** [comment]
Closing due to an incomplete description; feel free to re-open this and expand the `[object Object]` error string if it still happens :) Overall it sounds like you need to register a `.on('error', (...` handler
