### ISSUE TITLE
seqAudit=true issue

### ISSUE THREAD

**Issue by MRazva** [bitfinexcom/bitfinex-api-node#193]
hello guys, could you please help understand where the following issue comes from, I have set seqAudit=true as in the example:

Error: invalid auth seq #; last 71, got 192
    at WSv2._onWSMessage (/home/ubuntu/buroka/node_modules/bitfinex-api-node/lib/transports/ws2.js:351:30)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/home/ubuntu/buroka/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/ubuntu/buroka/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/ubuntu/buroka/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/ubuntu/buroka/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/ubuntu/buroka/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/ubuntu/buroka/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)

**Comment by nemozny** [comment]
Hi, same for me. I just thought the packets were lost.
This option is totally unusable for me, due to very high number of above errors.

**Comment by hems** [comment]
I get this error when i cancel an order on Bitfinex website

**Comment by npomfret** [comment]
Still a problem on 2.0.4

**Comment by anwfr** [comment]
hello,
on my experience the library is unusable with seqAudit=true.
As soon as I submit or cancel orders, I keep getting errors
> Error: invalid pub seq #; last 12, got 23
