### ISSUE TITLE
Websocket still silently stops receiving data 

### ISSUE THREAD

**Issue by soliveira-vouga** [bitfinexcom/bitfinex-api-node#206]
This is in reference to #138 

I've subscribed to order books but I've noticed that after a few hours the socket stops receiving data. I have `autoReconnect` set to `true`

**Comment by gairom** [comment]
I have the same problem, can't reconnect.
I've tried to use the autoReconnect and also manually to close and open but every time I get error 'not opened'
Fatal uncaught exception crashed  Error: not opened
    at WebSocket.send (C:\BitJS\node_modules\bitfinex-api-node\node_modules\ws\lib\WebSocket.js:360:18)
    at WSv2.send (C:\BitJS\node_modules\bitfinex-api-node\lib\transports\ws2.js:964:14)
    at WSv2.bws.on (C:\BitJS\bfx.js:84:15)
    at WSv2.emit (events.js:160:13)
    at WSv2._onWSClose (C:\BitJS\node_modules\bitfinex-api-node\lib\transports\ws2.js:277:10)
    at WebSocket.emit (events.js:165:20)
    at WebSocket.emitClose (C:\BitJS\node_modules\bitfinex-api-node\node_modules\ws\lib\WebSocket.js:211:10)
    at _receiver.cleanup (C:\BitJS\node_modules\bitfinex-api-node\node_modules\ws\lib\WebSocket.js:199:39)
    at Receiver.cleanup (C:\BitJS\node_modules\bitfinex-api-node\node_modules\ws\lib\Receiver.js:520:15)
    at WebSocket.finalize (C:\BitJS\node_modules\bitfinex-api-node\node_modules\ws\lib\WebSocket.js:199:20)
    at TLSSocket.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) function (error, level, msg, meta) {
        console.log(error, level, msg, meta);
        process.exit(1); }

Any ideas?

**Comment by f3rno** [comment]
Fixed in #297, but feel free to re-open if new `autoReconnect` issues arise
