### ISSUE TITLE
 TypeError: Cannot read property '0' of undefined when connect to ticker stream

### ISSUE THREAD

**Issue by massmediagroup-28** [bitfinexcom/bitfinex-api-node#249]
I use this code 
```
const bitfinex = new Bitfinex({
  apiKey: '...',
  apiSecret: '...',

  ws: {
    autoReconnect: true,
    packetWDDelay: 10 * 1000,
    manageOrderBooks: true,
    transform: true,
  },
})

const btcusd = 'tBTCUSD'

  const ws = bitfinex.ws()

  ws.on('open', () => {
    console.log('open')
    ws.subscribeTicker(btcusd)
  })

  ws.onTicker({ symbol: btcusd }, (ticker) => {
    console.log('%s ticker: %j', btcusd, ticker)
  })

  ws.open()
```

and have error output like this: 
```
open
/home/user/work/massmedia/project/node_modules/bitfinex-api-node/lib/models/tick.js:44
    if (Array.isArray(arr[0])) {
                         ^

TypeError: Cannot read property '0' of undefined
    at Function.unserialize (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/lib/models/tick.js:44:26)
    at WSv2._handleTickerMessage (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/lib/transports/ws2.js:533:41)
    at WSv2._handleChannelMessage (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/lib/transports/ws2.js:408:19)
    at WSv2._onWSMessage (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/lib/transports/ws2.js:377:12)
    at WebSocket.emit (events.js:160:13)
    at Receiver._receiver.onmessage (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/user/work/massmedia/project/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:599:20)
```

what i'm doing wrong?

**Comment by f3rno** [comment]
@massmediagroup-28 please update to the latest `master` branch and try again; the `tick.js` model is now gone. I'll close this in the meantime, if it occurs again with the latest version please re-open.
