### ISSUE TITLE
Error: connect ETIMEDOUT 75.126.2.43:443 

### ISSUE THREAD

**Issue by hxu2k** [bitfinexcom/bitfinex-api-node#268]
Error: connect ETIMEDOUT 75.126.2.43:443
 at Object.exports._errnoException (util.js:1019:11)
 at exports._exceptionWithHostPort (util.js:1041:20)
 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
code:'ETIMEDOUT',
syscall:'connect',
address:'75.126.2.43'

This error has happened for over two weeks.

**Comment by hxu2k** [comment]
No errors anymore.  Closed itself.

**Comment by hxu2k** [comment]
This error is on and off.

**Comment by hxu2k** [comment]
I had never changed anything to my code.  It just suddenly got disconnected with this error.  Could be the site was blocked by my govt?

**Comment by f3rno** [comment]
@hxu2k hmm, where are you located?

**Comment by hxu2k** [comment]
No, the other one.  ;-)

在 2018年4月23日，下午11:35，Sergey Kovalevich <notifications@github.com<mailto:notifications@github.com>> 写道：


@hxu2k<https://github.com/hxu2k> Russia? =D

**Comment by hxu2k** [comment]
Hi Chris,

Thanks for your reply.  This error persists no matter I use VPN or not in China.  My node.js code with REST API v1.1 worked perfectly fine before.  Will try to host my code on a private server as suggested and see what happens.

Thanks,
H.

在 2018年5月2日，下午4:23，Cris Mihalache <notifications@github.com<mailto:notifications@github.com>> 写道：


@hxu2k<https://github.com/hxu2k> since it's a network issue, there's nothing we can do in the library to fix it. Can you try running your logic from a private server outside of China? Otherwise, when the VPN connection fails momentarily you will see this error.
