### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by BarnumD** [bitfinexcom/bitfinex-api-node#29]
Build failing with SyntaxError: Identifier 'url' has already been declared.  Getting this on my installation.  Also seen in the travis build.

**Comment by michelem09** [comment]
There is still this error:

```
 1) should emit an auth event when authorized
  9 passing (4s)
  1 failing
  1) WebSocket should emit an auth event when authorized:
     Uncaught Error: Uncaught, unspecified "error" event. ([object Object])
      at BitfinexWS.onMessage (ws.js:9:2663)
      at Receiver.ontext (node_modules/ws/lib/WebSocket.js:816:10)
      at node_modules/ws/lib/Receiver.js:477:18
      at Receiver.applyExtensions (node_modules/ws/lib/Receiver.js:364:5)
      at node_modules/ws/lib/Receiver.js:466:14
      at Receiver.flush (node_modules/ws/lib/Receiver.js:340:3)
      at Receiver.finish (node_modules/ws/lib/Receiver.js:482:12)
      at Receiver.expectHandler (node_modules/ws/lib/Receiver.js:457:31)
      at Receiver.add (node_modules/ws/lib/Receiver.js:95:24)
      at TLSSocket.realHandler (node_modules/ws/lib/WebSocket.js:800:20)
      at readableAddChunk (_stream_readable.js:176:18)
      at TLSSocket.Readable.push (_stream_readable.js:134:10)
      at TLSWrap.onread (net.js:563:20)
```

**Comment by michelem09** [comment]
Ok, it didn't pass the Auth test because the api keys are invalid.
Could you please update the `test/keys.json` file?

**Comment by robertkowalski** [comment]
build should work now! :)

**Comment by robertkowalski** [comment]
and: yes, you were right. the keys.json are outdated.
