### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by tetiv** [bitfinexcom/bitfinex-api-node#312]
Hello,
I tried this example:

```
const BFX = require('bitfinex-api-node')

const bfx = new BFX({
  apiKey: '...',
  apiSecret: '...',

  ws: {
    autoReconnect: true,
    seqAudit: true,
    packetWDDelay: 10 * 1000,
  }
})

const ws = bfx.ws()

ws.on('error', (err) => console.log(err))
ws.on('open', () => {
  ws.subscribeTrades('BTCUSD')
})

ws.onTrades({ pair: 'BTCUSD' }, (trades) => {
  console.log(`trades: ${JSON.stringify(trades)}`)
})
ws.onTradeEntry({ pair: 'BTCUSD' }, (trades) => {
  console.log(`te: ${JSON.stringify(trades)}`)
})
ws.onTradeUpdate({ pair: 'BTCUSD' }, (trades) => {
  console.log(`tu: ${JSON.stringify(trades)}`)
})

ws.open()
```
and got this error:
```
/home/CoinMate/node_modules/bitfinex-api-node/lib/transports/ws2.js:648
    const listenerGroups = Object.values(this._listeners)
                                  ^

TypeError: Object.values is not a function
    at WSv2._propagateMessageToListeners (/home/CoinMate/node_modules/bitfinex-api-node/lib/transports/ws2.js:648:35)
    at WSv2._handleTradeMessage (/home/CoinMate/node_modules/bitfinex-api-node/lib/transports/ws2.js:523:10)
    at WSv2._handleChannelMessage (/home/CoinMate/node_modules/bitfinex-api-node/lib/transports/ws2.js:406:19)
    at WSv2._onWSMessage (/home/CoinMate/node_modules/bitfinex-api-node/lib/transports/ws2.js:377:12)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/home/CoinMate/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/CoinMate/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/CoinMate/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/CoinMate/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/CoinMate/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/CoinMate/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:559:20)
```
my package.json:

```
{
  "name": "bin",
  "version": "1.0.0",
  "description": "",
  "main": "dtmodule.js",
  "dependencies": {
    "bitfinex-api-node": "^2.0.0-beta",
    "node-binance-api": "^0.4.29",
    "upper-case": "^1.1.3",
    "ws": "^4.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
I don't know what is wrong in my code.
Thank you for your answer.

Kind regards, MT

**Comment by ddeath** [comment]
@tetiv take a look here:
https://github.com/bitfinexcom/bitfinex-api-node/issues/273

You have probably an old version of node.

@f3rno this is at least second time. Maybe you could include a required version of the node into README?

**Comment by tetiv** [comment]
You are right. I had an old version of node from Fedora rpm distribution. Thank you.
