### ISSUE TITLE
Error: Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by seymar** [bitfinexcom/bitfinex-api-node#334]
I'm getting the following error:
```
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/myproject/node_modules/bitfinex-api-node/lib/models/order.js:3:17)
```
Required from:
https://github.com/bitfinexcom/bitfinex-api-node/blob/599df5037f15ea812399d5ab3cd1ebf0c48e12d1/lib/models/order.js#L3

The cause may be:
`bluebird` is not part of the dependency list in [`package.json`](/bitfinexcom/bitfinex-api-node/blob/master/package.json)

I am using **Node v10.1.0**

**Comment by f3rno** [comment]
@seymar a fix is pending merge, thanks for pointing it out :bowing_man:
