### ISSUE TITLE
RangeError: out of range index

### ISSUE THREAD

**Issue by michelem09** [bitfinexcom/bitfinex-api-node#34]
I'm getting this error but I can't understand the problem, do you have any hint?

```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/xxx/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/home/xxx/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:86:3)
    at TLSSocket.realHandler (/home/xxx/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
/home/xxx/node_modules/bitfinex-api-node/node_modules/ws/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
```

**Comment by robertkowalski** [comment]
Hi @michelem09, thanks for reporting!

I was not able to reproduce the issue.

Can you provide a code example how the error happens?

**Comment by michelem09** [comment]
I'm closing this because my app doesn't suffer it anymore but I didn't remember what module was that I updated to solve that issue. (or may be I updated Node.js? sorry didn't remember)

**Comment by vkalra** [comment]
I'm getting the same error.  I'll see if I can get you a reproducible test case.

**Comment by robertkowalski** [comment]
@vkalra thank you.

can you report which channels you subscribe? do you use the v2 API?

**Comment by michelem09** [comment]
My code was something like this:

```
var bitfinexWebsocket = new bitfinexApiNode.WS(),
    Ticker = mongoose.model('Ticker');

bitfinexWebsocket.on('open', function(err) {
    bitfinexWebsocket.subscribeTicker();
});

bitfinexWebsocket.on('ticker', function(pair, data) {
    try {
        var now = moment.utc().format(),
            ticker = {
                code: 'BTC-USD',
                price: parseFloat(data.lastPrice).toFixed(2),
                high: parseFloat(data.high).toFixed(2),
                low: parseFloat(data.low).toFixed(2),
                date: now
            };

        console.log(chalk.green('Got ticker data at ' + now));
        console.log(chalk.white(JSON.stringify(data)));

        Ticker.findOneAndUpdate(ticker, ticker, {
            upsert: true,
            new: true
        }, function(err, newTicker) {
            if (err) return console.log(chalk.red(err));
        });
    } catch (e) {
        if (e) console.log(chalk.red(e));
        failure++;
    }
});

bitfinexWebsocket.on('error', function(err) {
    console.log(chalk.red('BITFINEX ERR', err));
    return;
});
```

**Comment by robertkowalski** [comment]
After some investigation i found out that this is related to the websocket library we use. It happens in relation to certain node releases. See https://github.com/websockets/ws/issues/778

we will publish a new version soon, in the meantime you can try our master branch directly:

```
npm install https://github.com/bitfinexcom/bitfinex-api-node
```

Thanks for your patience!

**Comment by vkalra** [comment]
@robertkowalski Thanks!  And I was using v2.
