### ISSUE TITLE
Frequent - Error: unexpected server response (429)

### ISSUE THREAD

**Issue by adityamertia** [bitfinexcom/bitfinex-api-node#344]
Hi,
I am trying to place order  using websocket. However the code works fine sometimes and same code gives following error at other times. This is happening quite frequently and we are not crossing our limit of placing many orders simultaneously. This is essentially only one order placement.

```
Error: unexpected server response (429)
    at ClientRequest._req.on (/home/ec2-user/bitfinex/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:653:21)
    at ClientRequest.emit (events.js:160:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:548:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:599:20)

```
source code used:
```
const BFX = require('bitfinex-api-node')
const { Order } = require('bitfinex-api-node/lib/models')
const bfx = new BFX({
  apiKey: process.env.BITFINEX_API_KEY,
  apiSecret: process.env.BITFINEX_API_SECRET,
  ws: {
    autoReconnect: true,
    seqAudit: false,
    packetWDDelay: 10 * 1000
  }
})

//let ws2 = bfx.ws() //
//ws2 = bfx.ws(2)    // same client

const rest2 = bfx.rest(2, {
  // options
})

const ws = bfx.ws(2)

ws.on('error', (err) => console.log(err))
ws.on('open', ws.auth.bind(ws))

ws.once('auth', () => {
  const o = new Order({
    cid: Date.now(),
    symbol: 'tETHUSD',
    price: 570.00,
    amount: 0.02,
    type: Order.type.EXCHANGE_LIMIT
  }, ws)

  // Enable automatic updates
  o.registerListeners()

  o.on('update', () => {
    console.log(`order updated: ${o.serialize()}`)
  })

  o.on('close', () => {
    console.log(`order closed: ${o.status}`)
    ws.close()
  })

  o.submit().then(() => {
    console.log(`submitted order ${o.id}`)
  }).catch((err) => {
    console.error(err)
    ws.close()
  })
})

ws.open()
```

**Comment by MaxPovver** [comment]
429 is Too Many Requests error
it means that you are calling api too often

**Comment by adityamertia** [comment]
@MaxPovver If you see the above code its essentially a single call and not in a loop. There is no other code that is at work apart from this one test code. Only one call cannot generate too many requests. And this issue keeps coming on and off. Any other pointers?

**Comment by ddeath** [comment]
@adityamertia you still can get too many requests event if you have only one call.

For example if you have poor network connection. I think by default is autoReconnect true, so if you have a network issues you will be reconnecting frequently and it will cause 429.

Try logging how frequently your connection drops and reopens... Maybe the issue is there
