### ISSUE TITLE
Got TypeError: Cannot read property '0' of undefined when ws long time running

### ISSUE THREAD

**Issue by leepupu** [bitfinexcom/bitfinex-api-node#433]
Here minimal code basically from example:
```
const BFX = require('bitfinex-api-node');
let bfx = new BFX({
        ws: {
          autoReconnect: true,
          seqAudit: true,
          manageOrderBooks: true,
          transform: true,
          packetWDDelay: 10 * 1000
        }
      });
let bfxWS = bfx.ws();
bfxWS.subscribeOrderBook(/*a pair*/);
bfxWS.onOrderBook({ symbol: subscribePair }, (ob) => {
// do things here
});
```

After about 14 hours I got error from bfx-api-node-models and process crashed:
```
TypeError: Cannot read property '0' of undefined
    at Function.updateArrayOBWith (/app/node_modules/bfx-api-node-models/lib/order_book.js:442:20)
    at WSv2._updateManagedOB (/app/node_modules/bitfinex-api-node/lib/transports/ws2.js:684:15)
    at WSv2._handleOBMessage (/app/node_modules/bitfinex-api-node/lib/transports/ws2.js:638:24)
    at WSv2._handleChannelMessage (/app/node_modules/bitfinex-api-node/lib/transports/ws2.js:577:19)
    at WSv2._onWSMessage (/app/node_modules/bitfinex-api-node/lib/transports/ws2.js:548:12)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onread (net.js:639:20)
```

versions:
```
bitfinex-api-node : 2.0.2
bfx-api-node-models: 1.0.2
```

Running on GKE, network might not be the problem.

**Comment by f3rno** [comment]
@leepupu can you enable logging and post the last few messages before this error? Specifically the incoming order book packets; it looks like the order book has an empty price level, which should never happen. This is very difficult to debug on my end.

**Comment by leepupu** [comment]
@f3rno 
I enable logging with DEBUG='bfx:*' and got some logs before problem happened. 
```
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5093.1,0,-1],17684742]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5093.3,0,-1],17684743]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5093.8,0,-1],17684744]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5093.9,0,-1],17684745]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5095.2,0,-1],17684746]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5095.4,0,-1],17684747]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5095.6,0,-1],17684748]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5095.9,0,-1],17684749]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5096.5,0,-1],17684750]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5096.8,0,-1],17684751]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5096.9,0,-1],17684752]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5097.4,0,-1],17684753]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5097.6,0,-1],17684754]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5097.7,0,-1],17684755]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5098.3,0,-1],17684756]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5098.6,0,-1],17684757]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5099.1,0,-1],17684758]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5099.3,0,-1],17684759]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5099.6,0,-1],17684760]
Thu, 15 Nov 2018 09:55:06 GMT bfx:ws2 recv msg: [102953,[5103.6,5,17.49183845],17684761]
TypeError: Cannot read property '0' of undefined
  ...
```

**Comment by leepupu** [comment]
I tried to dump _orderBooks when problem happened, and i got

```
  tBTCEUR: [
   0:  null    
   1:  null    
   2:  null    
  ]
  tBTCUSD: [50]   
  tEOSBTC: [50]   
  tEOSETH: [50]   
  tEOSUSD: [50]   
  tETCBTC: [50]   
  tETCUSD: [50]   
  tETHBTC: [50]   
  tETHUSD: [50]   
...
```

**Comment by leepupu** [comment]
Finally I got the problem,
When server clear all the orders (maybe rebuild for syncing?), the _orderBooks[symbol] will become empty array and code [here](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/transports/ws2.js#L650) will generate an orderbook instance with something like this:

```
OrderBook {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  raw: true,
  bids: [ [] ],
  asks: [] }
```

And this instance pass to my callback function which think bids/asks will always be array of three element and override the element in this empty array cause the structure in _orderBooks broken. So it's basically our problem.

The Orderbook model may do more check for empty orderbook scenario.

Thanks.

**Comment by f3rno** [comment]
@leepupu I'm glad you figured it out! I've pushed a commit to `bfx-api-node-models` to prevent inserting an empty array when the update packet is empty, this should prevent the problem in the future so your logic does not fill it with `null`.

**Comment by leepupu** [comment]
Thanks a lot! I'll upgrade it to latest version.
