### ISSUE TITLE
REST version 1 SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by nedievas** [bitfinexcom/bitfinex-api-node#64]
```
const BFX = require('bitfinex-api-node')
const bfx = new BFX()
const bfx_rest = bfx.rest
```

sends me this error:
```
...node_modules/bitfinex-api-node/index.js:11
  constructor (apiKey, apiSecret, opts = { version: 1, transform: false }) {
                                       ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/rebootfin/test/zenbot/extensions/bitfinex/exchange.js:1:75)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by robertkowalski** [comment]
Please update to the latest Node.js stable LTS version (6.10.3)
