### ISSUE TITLE
TypeError: format.replace is not a function

### ISSUE THREAD

**Issue by nedievas** [bitfinexcom/bitfinex-api-node#69]
Hello, I get this error: 

```
/home/bitfinex/zenbot/node_modules/numbro/numbro.js:183
            escapedFormat = format.replace(/\{[^\{\}]*\}/g, '');
                                   ^

TypeError: format.replace is not a function
    at formatNumbro (/home/bitfinex/zenbot/node_modules/numbro/numbro.js:183:36)
    at Object.format (/home/bitfinex/zenbot/node_modules/numbro/numbro.js:1144:20)
    at /home/bitfinex/zenbot/lib/engine.js:398:87
    at /home/bitfinex/zenbot/lib/engine.js:341:11
    at /home/bitfinex/zenbot/extensions/exchanges/bitfinex/exchange.js:83:9
    at Request.error1 [as _callback] (/home/bitfinex/zenbot/node_modules/bitfinex-api-node/rest.js:89:12)
    at Request.self.callback (/home/bitfinex/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bitfinex/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/bitfinex/zenbot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

for this part of code with new version pull:
```
client.ticker(pair, function (err, body) {
        if (err) return cb(err)
        cb(null, {bid: body.bid, ask: body.ask})
      })
```

**Comment by robertkowalski** [comment]
the error seems to happen in one of your dependencies, `numbro`

what are you passing to numbro in `/home/bitfinex/zenbot/lib/engine.js:398:87`?

**Comment by nedievas** [comment]
```
getQuote(function (err, quote) {
          if (err) {
            err.desc = 'could not execute ' + signal + ': error fetching quote'
            return cb(err)
          }
          var mid_price = n(quote.ask).add(quote.bid).divide(2)
          if (signal === 'buy') {
            price = n(mid_price).subtract(n(mid_price).multiply(so.markup_pct / 100)).format(s.product.increment, Math.floor)
```

> price = n(mid_price).subtract(n(mid_price).multiply(so.markup_pct / 100))**.format**(s.product.increment, Math.floor)

**Comment by robertkowalski** [comment]
sorry, this is not a api-client issue.
