### ISSUE TITLE
What does 'order' look like in ws2?

### ISSUE THREAD

**Issue by hurryhx** [bitfinexcom/bitfinex-api-node#71]
I want to use 'submitOrder(order)' function in ws2. But I cannot find what 'order' looks like in this repo. I tried to use the doc (http://docs.bitfinex.com/v2/reference/#ws-auth-order-new) and tried json:
`
  {
    "gid": 1,
    "cid": 12345,
    "type": "LIMIT",
    "symbol": "tBTCUSD",
    "amount": "1.0",
    "price": "500",
    "hidden": 0
  }
`
as an order. But I got this error: 

Error: Uncaught, unspecified "error" event. ([object Object])
    at BitfinexWS2.emit (events.js:163:17)
    at BitfinexWS2.onMessage (/Users/hurryhx/tmp/node_modules/bitfinex-api-node/ws2.js:81:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/hurryhx/tmp/node_modules/ws/lib/WebSocket.js:816:10)
    at /Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:364:5)
    at /Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.finish (/Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:482:12)
    at Receiver.expectHandler (/Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:457:31)
    at Receiver.add (/Users/hurryhx/tmp/node_modules/ws/lib/Receiver.js:95:24)
    at TLSSocket.realHandler (/Users/hurryhx/tmp/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:551:20)

So can you help me use submitOrder in ws2? Thanks!

**Comment by robertkowalski** [comment]
Hi @hurryhx,

thanks for asking. Here is an example payload:

```js
[
  0,
  "on",
  null,
  {
    "gid": 1,
    "cid": 12345,
    "type": "LIMIT",
    "symbol": "tBTCUSD",
    "amount": 1,
    "price": 500,
    "hidden": 0
  }
]
```

hope that helps!
