### ISSUE TITLE
STOP state Json parsing error

### ISSUE THREAD

**Issue by dmitruis** [bitfinexcom/bitfinex-api-node#72]
I'm getting the following error randomly when running the websocket for an extensive amount of time and can't figure out where it's coming from: 
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Invalid JSON (Unexpected "T" at position 0 in state STOP)
    at Parser.proto.charError (node_modules\jsonparse\jsonparse.js:90:16)
    at Parser.proto.write (node_modules\jsonparse\jsonparse.js:154:23)
    at Stream.<anonymous> (node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (node_modules\through\index.js:26:11)
    at Request.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> node_modules\request\request.js:1088:12)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback

Are you handling the 20051, 20060, and 20061 codes from the websocket mentioned under info codes: http://docs.bitfinex.com/docs/ws-general? I imagine the websocket sends an HTML response in that case and the json parse is thus erroring. 

Thanks for taking a look!

**Comment by robertkowalski** [comment]
@dmitruis thanks for reporting. right now we are looking into the issue

**Comment by robertkowalski** [comment]
@dmitruis fix coming soon!

**Comment by robertkowalski** [comment]
@dmitruis i opened https://github.com/bitfinexcom/bitfinex-api-node/pull/74

**Comment by dmitruis** [comment]
awesome thanks!
